name: .NET

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
        with:
          fetch-depth: 0
      - name: Restore tools
        run: dotnet tool restore
      - uses: cake-build/cake-action@a6eb054329257c9e70a6c6bf01747ad6e1d9d52b # tag=v1
        name: Building
        with:
          script-path: build.cake
          cake-version: 2.2.0
      - uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3
        if: always()
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3.1.0
        with:
          path: |
            .artifacts/installers/*.exe
            .artifacts/packages/**/*.nupkg
