name: .NET (Non-Main)

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-20.04, macos-11]

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          fetch-depth: 0
      - uses: actions/cache/@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: |
            ~/.nuget/packages
            !~/.nuget/packages/unwanted
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a # v3
        with:
          global-json-file: global.json
      - name: Restore tools
        run: dotnet tool restore
      - uses: cake-build/cake-action@a6eb054329257c9e70a6c6bf01747ad6e1d9d52b # tag=v1
        name: Building
        with:
          script-path: build.cake
          cake-version: tool-manifest
      - uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2 # v3
        if: always()
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:

          path: |
            .artifacts/executables/*
            .artifacts/packages/**/*.nupkg
