name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0
      - name: Restore tools
        run: dotnet tool restore
      - uses: cake-build/cake-action@a6eb054329257c9e70a6c6bf01747ad6e1d9d52b # tag=v1
        name: Building
        with:
          script-path: build.cake
          cake-version: 2.2.0
      - uses: actions/upload-artifact@v3.1.0
        with:
          path: |
            .artifacts/installers/*.exe
            .artifacts/packages/**/*.nupkg
