name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Restore tools
      run: dotnet tool restore
    - uses: cake-build/cake-action@v1
      name: Building
      with:
        script-path: build.cake
        cake-version: 0.38.5
        cake-bootstrap: true
