name: Lint Code Base

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  super_linter:
    name: Lint with Super Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Lint Code Base
        uses: github/super-linter@bb2d833b08b6c288608686672b93a8a4589cdc49 # tag=v4.9.7
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name != 'pull_request' }}
          VALIDATE_DOCKERFILE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: "."
          OUTPUT_FORMAT: "tap"
