name: Lint Code Base

on:
  push:
  pull_request:

jobs:
  super_linter:
    name: Lint with Super Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Lint Code Base
        uses: github/super-linter@bb2d833b08b6c288608686672b93a8a4589cdc49 # tag=v4.9.7
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: "."
          OUTPUT_FORMAT: "tap"
