name: Lint Code Base

on:
  push:
    branches: [master]
  pull_request:

jobs:
  super_linter:
    name: List with Super Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Lint Code Base
        uses: github/super-linter@v3.14.5
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: "."
